HyperParameters:
  _target_: experiment_params.HyperParameters
  batch_size: 200
  epochs: 10
  burnin_offset: 50
  model_batch_size: 200
  optimizer_class: Adam
  optimizer_params:
    lr: 0.1
  scheduler_class: ExponentialLR
  scheduler_params:
    gamma: 0.9
ModelParameters:
  _target_: experiment_params.ModelParameters
  model_class: MultivariateGaussianModel
  start_params:
    mu_0:
      _target_: helper_tools.convert_to_tensor
      data:
      - 2.0
      - 2.0
    Sigma_0:
      _target_: helper_tools.convert_to_tensor
      data:
      - - 2.0
        - 0.0
      - - 0.0
        - 1.0
SamplingParameters:
  _target_: experiment_params.SamplingParameters
  sampler_class: MALASampler
  epsilon:
    _target_: helper_tools.convert_to_tensor
    data: 0.10000000149011612
  start_batch:
    _target_: helper_tools.convert_to_tensor
    data:
    - - 0.0
      - 0.0
    - - 0.0
      - 0.0
    - - 0.0
      - 0.0
    - - 0.0
      - 0.0
    - - 0.0
      - 0.0
  L: 3
  M:
    _target_: helper_tools.convert_to_tensor
    data:
    - - 1.0
      - 0.0
    - - 0.0
      - 1.0
LikelihoodParameters:
  _target_: experiment_params.LikelihoodParameters
  likelihood_class: RecoveryLikelihood
  perturbation_var:
    _target_: helper_tools.convert_to_tensor
    data: 1.0
