HyperParameters:
  _target_: likelihood_inference.HyperParameters
  batch_size: 200
  epochs: 10
  burnin_offset: 20
  model_batch_size: 1000
  likelihood_class: RecoveryLikelihood
  optimizer_class: Adam
  optimizer_params:
    lr: 0.1
  scheduler_class: null
  scheduler_params:
    gamma: 0.9
ModelParameters:
  _target_: likelihood_inference.ModelParameters
  model_class: UnivModeratedCosine
  target_params:
    W:
      _target_: helper_tools.convert_to_tensor
      data: 1.0
    mu:
      _target_: helper_tools.convert_to_tensor
      data: 2.0
  start_params:
    W:
      _target_: helper_tools.convert_to_tensor
      data: -0.5
    mu:
      _target_: helper_tools.convert_to_tensor
      data: -2.0
  requires_adapter: true
  perturbation_var:
    _target_: helper_tools.convert_to_tensor
    data: 1.5
SamplingParameters:
  _target_: likelihood_inference.SamplingParameters
  sampler_class: HMCSampler
  epsilon:
    _target_: helper_tools.convert_to_tensor
    data: 0.1
  L: 3
  M:
    _target_: helper_tools.convert_to_tensor
    data:
    - - 1.0
